kind:       Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name:      root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lunics/argocd.git
    path:    root-app
    targetRevision: HEAD
  destination:
    namespace: argocd
    server:    https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
