# all values: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

argo-cd:
  namespaceOverride: argocd
  dex:                
    enabled: false    # disable integration with external auth providers
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure    # for Web UI over HTTP
  # fullnameOverride: "argocd"
  # configs.secret.argocdServerAdminPassword: WEhNfUoyZmghSUpKVzBIW0ExdnV8Igo=
